name: base_scaffold
description: A Flutter package for base scaffold.
homepage: https://github.com/Pinkal7600/base_scaffold
authors:
  - Pinkal Patel <pinkaljpael1995@gmail.com>

version: 0.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
